### ISSUE TITLE
21.03.2019 - Instagram - Schulen

### ISSUE THREAD

**Issue by flowerner** [dreibein/project-social-media#1]

**Comment by stefan-feldbauer** [comment]
![Mockup_1](https://user-images.githubusercontent.com/34537187/54747595-a03a4e80-4bcf-11e9-99a1-858da07936ec.jpg)
![Mockup_2](https://user-images.githubusercontent.com/34537187/54747597-a0d2e500-4bcf-11e9-83c8-3f60cd69894c.jpg)
![Mockup_3](https://user-images.githubusercontent.com/34537187/54747598-a0d2e500-4bcf-11e9-8500-dbcb31768176.jpg)
Für die Gerhardinger und Maristen Realschule Cham wurde die Webpräsenz neu konzipiert und realisiert. Mehr über das Projekt erfährst du unter www.agentur-dreibein.de/projekte

**Comment by flowerner** [comment]
Find ich gut, aber Links im Post gehen nicht, wenn dann müsstest evtl. zum Link in der Bio das Projekt hinzufügen im Linktree @stefan-feldbauer

**Comment by stefan-feldbauer** [comment]
Link hab ich in der Bio ergänzt

"Für die Gerhardinger und Maristen Realschule Cham wurde die Webpräsenz neu konzipiert und realisiert. Mehr über das Projekt erfährst du unter dem Link in unserer Bio."

**Comment by flowerner** [comment]
Launch :-)
