### ISSUE TITLE
03.05.19 ELIAS • IN • SZENE 

### ISSUE THREAD

**Issue by barbara-bindl** [dreibein/project-social-media#10]
Man sieht ihn viel zu selten auf unserem Instagram Profil. Warum? Naja.... Weil er der Mann ist, der unsere genialen Fotos schießt! 
Jetzt aber, haben wir ihn mal vor die Linse bekommen, und siehe da, dieser Typ mit sympathischen Lächeln beigeistert Tag für Tag uns und unsere Kunden aufs Neue. 

Wir haben euch neugierg gemacht? Dann werft einen Blick auf unsere Website und lasst euch von unseren Fotos inspirieren. Den Link findet ihr in der Bio. 

PEACE OUT INS WOCHENENDE! Genießt eure freien Tage!

#agenturdreibein #agency #agencylife #photographer #photography #funatwork #happy #tgif #peace 

![elias](https://user-images.githubusercontent.com/48916705/57122899-e31b4480-6d7f-11e9-98ea-826dac8be8c9.jpg)

**Comment by barbara-bindl** [comment]
Habt ihr noch andere Titelvorschläge?

**Comment by flowerner** [comment]
Genial statt geil bitte 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by flowerner** [comment]
Und wie immer: links im Post gehen in Instagram nicht 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by barbara-bindl** [comment]
Man sieht ihn viel zu selten auf unserem Instagram Profil. Warum? Naja.... Weil er der Mann ist, der unsere genialen Fotos schießt!
Jetzt aber, haben wir ihn mal vor die Linse bekommen, und siehe da, dieser Typ mit sympathischen Lächeln beigeistert Tag für Tag uns und unsere Kunden aufs Neue.

Wir haben euch neugierg gemacht? Dann werft einen Blick auf unsere Website und lasst euch von unseren Fotos inspirieren. Den Link findet ihr in der Bio.

PEACE OUT INS WOCHENENDE! Genießt eure freien Tage!

#agenturdreibein #agency #agencylife #photographer #photography #funatwork #happy #tgif #peace
