### ISSUE TITLE
06.05 • HEY • HO • MONDAY

### ISSUE THREAD

**Issue by barbara-bindl** [dreibein/project-social-media#11]
Wir wünschen euch nen' super Start in die neue Arbeitswoche!
Stefan ist schon in seinem Workflow. Seine Aufgabe ist es, die Websites unserer Kunden technisch umzusetzen. Wichtig dabei ist, dass die Seite am Ende nicht nur schön aussieht und ein tolles Design hat, sondern auch eine einwandfreie Funktionalität dahinter steckt. 
Denn was bringt dem Kunden eine schöne Website, wenn sie aber technisch gesehen nicht gut ist? Richtig: Nichts!

Gespannt an den Projekten, die Stefan und unsere Kollegen bereits umgesetzt haben? Den Link findet ihr in unserer Bio.

#agenturdreibein #agency #agencylife #frontenddeveloper #webdesign #design #macbookpro #development #css #helloworld #mondaymotivation 

![stefan](https://user-images.githubusercontent.com/48916705/57209582-47851080-6fd9-11e9-8908-06f956a2b10a.jpg)

**Comment by flowerner** [comment]
Find ich gut, aber den Text würde ich etwas umschreiben, um zu zeigen, dass er Teil eines großen Teams ist.

Wir wünschen euch einen genialen Start in die neue Arbeitswoche!
Stefan ist schon in seinem Workflow an diesem Monat. Er gehört zu unserem Team der Frontend Developer. Sie sorgen dafür, dass aus durchdachten Designs hochwertige Websites entstehen, die nicht nur großartig aussehen, sondern auch funktionieren und unseren Kunden einen echten Mehrwert bringen, damit unsere Seiten viel mehr sind als digitale Visitenkarten.

Gespannt an den Projekten, die Stefan und unsere Kollegen bereits umgesetzt haben? Den Link findet ihr in unserer Bio.

#agenturdreibein #agency #agencylife #frontenddeveloper #webdesign #design #macbookpro #development #css #helloworld #mondaymotivation
