### ISSUE TITLE
10.05.2019 PRAKTIKUM • BEI • DREIBEIN

### ISSUE THREAD

**Issue by barbara-bindl** [dreibein/project-social-media#12]
Diese Woche hat uns unser Praktikant Thomas tatkräftig unterstützt. Er erhielt Einblicke in den Bereich Fotografie und Design, hat uns zu Kundenterminen begleitet und war beim Agenturalltag der Agentur Dreibein immer live dabei. 

Du hast auch Interesse an einem Praktikum bei uns? Dann ruf' uns unter der 09971 129 017 - 0 an und stelle Dich kurz vor. Wir freuen uns von Dir zu hören. 

Schönes Wochenende! 

#agenturdreibein #agencylife #praktikum #design #webdevelopment #photography #nicetomeetyou

![thomas_1](https://user-images.githubusercontent.com/48916705/57523259-cdc88c00-7324-11e9-9e1f-c5ffa3e8a2e0.jpg)
![thomas_2](https://user-images.githubusercontent.com/48916705/57523260-cdc88c00-7324-11e9-84e7-c137aeb30654.jpg)

**Comment by flowerner** [comment]
Sehr cool, die Sortierung so, dass wir zuerst das Bild und dann ihn nehmen. Posten dürfen wir es sicher oder?

**Comment by barbara-bindl** [comment]
ja, laut Elias dürfen wir es posten

**Comment by flowerner** [comment]
Okidoki
