### ISSUE TITLE
14.05.19 - IST • WERBUNG • WICHTIG?

### ISSUE THREAD

**Issue by stefan-feldbauer** [dreibein/project-social-media#13]
![quote_henry_ford_14_05](https://user-images.githubusercontent.com/34537187/57675849-61e76b80-7623-11e9-8956-7b1fb2426613.png)

Unsere Antwort: JA!
Werbung ist aus unserem Alltag kaum mehr weg zu denken. Egal wohin der Blick fällt, fast überall kann man in irgendeiner Art Werbung entdecken. Um aus dieser Masse heraus zu stechen und dein Unternehmen interessant zu gestalten, ist eine gute Marketingstrategie überlebenswichtig. Triff die richtige Entscheidung und ruf uns unter 09971 129 017-0 an!

**Comment by sebssch** [comment]
Würde die Kommas immer ans Ende setzten so denke ich ist das lesen angenehmer.

Wer aufhört zu werben,
um so Geld zu sparen,
kann ebenso seine Uhr anhalten,
um Zeit zu sparen.


@stefan-feldbauer

**Comment by stefan-feldbauer** [comment]
![quote_henry_ford_14_05](https://user-images.githubusercontent.com/34537187/57677806-02d82580-7628-11e9-91b4-c7068db0c8ff.png)

**Comment by sebssch** [comment]
Also ich finds besser. etwas klein aber sonst würde es wohl am Rand kleben..

**Comment by flowerner** [comment]
Eine textlich gute Ergänzung zu dem Zitat gibts in diesem Text: https://www.existenzgruender-helfer.de/2012/09/03/wer-aufhoert-zu-werben-um-geld-zu-sparen-kann-ebenso-die-uhr-anhalten-um-zeit-zu-sparen/
Finde ich wichtig zu sagen, Werbung ist nicht gleich Werbung

**Comment by stefan-feldbauer** [comment]
Unsere Antwort: JA!
Werbung ist aus unserem Alltag kaum mehr weg zu denken. Egal wohin der Blick fällt, fast überall kann man in irgendeiner Art Werbung entdecken. Marketing muss eben darum einen festen Teil in der Kostenstruktur darstellen, um Produkte und Dienstleistungen erfolgreich zu verkaufen. Eine gute Marketingstrategie ist überlebenswichtig, um einerseits aus der Masse herauszustechen und das Unternehmen interessant und auffällig zu gestalten. Triff die richtige Entscheidung und ruf uns unter der 09971 129 017-0 an!

**Comment by flowerner** [comment]
Ist so in Ordnung :) letzter Satz noch raus, das wirkt so als bräuchten wir gerade Aufträge, deshalb einfach ersatzlos streichen

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by barbara-bindl** [comment]
ist online :)
