### ISSUE TITLE
05.07 DESIGN • IN STEIN • GEMEISSELT

### ISSUE THREAD

**Issue by barbara-bindl** [dreibein/project-social-media#14]
![mockup_instagram](https://user-images.githubusercontent.com/48916705/60705757-3b99ca00-9f08-11e9-9272-00caaa240dec.jpg)
![2](https://user-images.githubusercontent.com/48916705/60707034-1064aa00-9f0b-11e9-87e9-09abcd979a8d.jpg)
![3](https://user-images.githubusercontent.com/48916705/60707035-1064aa00-9f0b-11e9-8fdc-738299e6779c.jpg)
![4](https://user-images.githubusercontent.com/48916705/60707038-10fd4080-9f0b-11e9-948b-580ea747e783.jpg)

Genau wie Marmor-Granit Maier machen wir uns mit derselben Begeisterung an unsere Projekte – wir haben die bisherige Website überarbeitet und eine neue moderne Version konzipiert. 
Mit eigens inszenierten Bildern rückt die Vielzahl an Gestaltungsmöglichkeiten von Bädern, Küchenarbeitsplatten und Treppenanlagen aus Naturstein in den Vordergrund und verweist zusätzliche auf das Unternehmen selbst, seine Referenzen und Karrieremöglichkeiten. Entdeckt die Vielfalt von Marmor-Granit Maier – mehr als nur Steine – auf www.maiergranit.de
Weitere Infos zum Projektablauf findet ihr über den Link in unserer Bio. 

#agenturdreibein #agencylife #webdesign #design #stone #craft #web #coding #code #mediadesign #webdesigner #online #agency

**Comment by flowerner** [comment]
Wenn Bilder in der Website noch ergänzt sind, von meiner Seite her freigegeben. Sehr gut!
