### ISSUE TITLE
17.04. Instagram - Mitarbeiterfoto Tobi

### ISSUE THREAD

**Issue by stefan-feldbauer** [dreibein/project-social-media#2]
![Tobi](https://user-images.githubusercontent.com/34537187/54751752-2bb9dc80-4bdc-11e9-8722-1c987d6902dd.jpg)
BEI • DER • ARBEIT

**Comment by toblr** [comment]
Würde für heute den Issue #3 vorziehen! :)

**Comment by stefan-feldbauer** [comment]
ORDNUNG • MUSS • SEIN

...denn die ist bei der Erstellung neuer, genialer Websites nicht wegzudenken!
•
•
•
#ordnungmusssein #ordnung #work #agenturdreibein #agencylife #aufräumen #websites #webdesign #webdeveloper #frontend #backend #design #developer #digital #bmw #gucci #apple #iphone #macbook
