### ISSUE TITLE
25.03.2019 - Schindler Event-Recap

### ISSUE THREAD

**Issue by toblr** [dreibein/project-social-media#3]
Würde heute paar Bilder des Schindler-Events posten. Gerne in die Story paar Videos und Fotos, als extra Post könnten wir eine der folgenden Bilder posten:

![DREI1615](https://user-images.githubusercontent.com/16285278/54908719-d554e280-4ee8-11e9-851a-78854801aaf5.jpg)
![_REI1485](https://user-images.githubusercontent.com/16285278/54908786-f74e6500-4ee8-11e9-8117-254b04bffe23.jpg)
![_REI1478](https://user-images.githubusercontent.com/16285278/54908788-f74e6500-4ee8-11e9-9454-5319d460b19f.jpg)
![_REI1471](https://user-images.githubusercontent.com/16285278/54908790-f74e6500-4ee8-11e9-99c2-2cefb009c810.jpg)
![_REI1469](https://user-images.githubusercontent.com/16285278/54908804-fc131900-4ee8-11e9-8626-44e31a6eb871.jpg)
![_REI1463](https://user-images.githubusercontent.com/16285278/54908805-fc131900-4ee8-11e9-861b-257af8adadc8.jpg)

Und hier noch die Sachen für die Story in einem ZIP-Archiv:
https://we.tl/t-4K6dTynU1z

**Comment by stefan-feldbauer** [comment]
ZUSAMMEN • SCHAFFEN • SCHINDLER
Am Freitag durften wir die neue Arbeitgebermarke der Schindler Fassaden & Fenster GmbH vor der gesamten Belegschaft präsentieren. Mit über 350 Leuten wurde die neue Marke bei Häppchen und dem ein oder anderen Bier gefeiert, bis es dann in das wohlverdiente Wochenende ging.

Wer sich selbst noch ein Bild machen möchte, kann bei @schindlerroding oder unter zusammen-schaffen.de vorbeischauen!


![54908786-f74e6500-4ee8-11e9-8117-254b04bffe23](https://user-images.githubusercontent.com/34537187/54918844-93836680-4eff-11e9-94d0-4eb671038164.jpg)
![54908788-f74e6500-4ee8-11e9-9454-5319d460b19f](https://user-images.githubusercontent.com/34537187/54918845-941bfd00-4eff-11e9-87f9-cd611622a6f2.jpg)
![54908790-f74e6500-4ee8-11e9-99c2-2cefb009c810](https://user-images.githubusercontent.com/34537187/54918846-941bfd00-4eff-11e9-991e-ce0d83b4af75.jpg)
![54908805-fc131900-4ee8-11e9-861b-257af8adadc8](https://user-images.githubusercontent.com/34537187/54918847-941bfd00-4eff-11e9-97bc-915832379dcd.jpg)

und dann noch ne story

**Comment by toblr** [comment]
Okay passt, kannst du gerne posten! 👍

**Comment by dreibein** [comment]
#zusammenschafen Hashtag fehlte noch ist ergänzt
