### ISSUE TITLE
28.04.2019 - Instagram - Projekt Magna

### ISSUE THREAD

**Issue by stefan-feldbauer** [dreibein/project-social-media#4]
![Mockup_01](https://user-images.githubusercontent.com/34537187/55004088-dca7e900-4fd9-11e9-8044-f2ed5cca86f0.jpg)
![Mockup_02](https://user-images.githubusercontent.com/34537187/55004090-dca7e900-4fd9-11e9-9e26-e003c6efce3f.jpg)
@sebssch vllt kannst du bis Donnerstag noch nen ganz kurzen Text für Instagram schreiben?

**Comment by sebssch** [comment]
Vorschlag: @stefan-feldbauer 

SÜS - SÜSER - MAGNA SWEETS
Für den Werbemittelhänder aus Moorenweis bei München haben wir den Onlineauftritt neu gestaltet und technisch generalüberholt. Mehr zum Projekt und den spannenden Features erfährst du unter dem Link in unserer Bio.

**Comment by stefan-feldbauer** [comment]
SÜS • SÜSSER • MAGNA SWEETS

Für den Werbemittelhändler aus Moorenweis bei München haben wir den Onlineauftritt neu gestaltet und technisch generalüberholt. Mehr zum Projekt und den spannenden Features erfährst du unter dem Link in unserer Bio.
•
•
•
#agenturdreibein #agencylife #sweets #webdesign #werbemittel #advertisingmaterials #sweet #products #pink #design #web #coding #code #mediadesign #webdesigner #online #agency

**Comment by flowerner** [comment]
Go von meiner Seite. Super 👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by flowerner** [comment]
Fb bitte auch 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toblr** [comment]
Ich poste sowohl Facebook, als auch Instagram! @stefan-feldbauer
