### ISSUE TITLE
02.04.2019 - Schindler

### ISSUE THREAD

**Issue by stefan-feldbauer** [dreibein/project-social-media#6]
![Mockup_01](https://user-images.githubusercontent.com/34537187/55392731-2e052a80-553c-11e9-9fe7-982e764cff52.jpg)
![dreifoto_WEB_Archiv_Schindler_DREI7171](https://user-images.githubusercontent.com/34537187/55392783-42e1be00-553c-11e9-8871-63f03630b3f5.jpg)
![dreifoto_WEB_Archiv_Schindler_DREI7370](https://user-images.githubusercontent.com/34537187/55392792-470ddb80-553c-11e9-8775-f71a9445be0f.jpg)

EMPLOYER • BRANDING • SCHINDLER

Wir freuen uns, die Ergebnisse des Employer Brandings für das Unternehmen Schindler Fenster & Fassaden nun auch euch präsentieren zu können. Mehr über das Projekt erfährst du über den Link in unserer Bio.

**Comment by flowerner** [comment]
Optimal, kann raus
